<?php
defined('BASEPATH') OR exit('No direct script access allowed');
?><!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Terms of Use - RandomAddress</title>

  <link rel="stylesheet" href="<?php echo base_url();?>static/css/custom.css">

</head>
<body class="min-h-screen flex flex-col bg-gradient-main">

  <?php echo $header; ?>

  <main class="flex-1">
    <div class="container mx-auto max-w-4xl px-4 sm:px-6 lg:px-8 py-12">
      <h1 class="text-3xl lg:text-4xl font-light text-gray-900 mb-8">Terms of Use</h1>

      <div class="bg-white/70 backdrop-blur-sm rounded-3xl p-8 lg:p-10 shadow-lg border border-gray-100">
        <div class="prose prose-lg max-w-none">
          <p class="text-gray-600 mb-6"><strong>Last Updated: February 2025</strong></p>

          <p class="text-gray-700 leading-relaxed mb-6">Welcome to <strong>RandomAddress.com</strong> ("Website", "we", "us", or "our"). By accessing or using our website and services, you agree to comply with and be bound by the following Terms of Use. If you do not agree with any part of these terms, please do not use our website.</p>

          <h2 class="text-2xl font-light text-gray-900 mt-8 mb-4">1. Use of Services</h2>
          <ul class="text-gray-700 leading-relaxed mb-6 space-y-2">
            <li>RandomAddress provides random data generation tools for various purposes. The generated data is provided "as is" and should not be used for illegal activities.</li>
            <li>You are responsible for ensuring that your use of our services complies with all applicable laws and regulations.</li>
            <li>We do not guarantee the accuracy, uniqueness, or suitability of any generated data.</li>
          </ul>

          <h2 class="text-2xl font-light text-gray-900 mt-8 mb-4">2. Intellectual Property</h2>
          <ul class="text-gray-700 leading-relaxed mb-6 space-y-2">
            <li>All content, designs, and tools available on RandomAddress.com are owned by or licensed to us and protected by copyright, trademark, and other intellectual property laws.</li>
            <li>You may use our tools for personal or commercial purposes, but you may not resell, redistribute, or modify our services without prior written permission.</li>
          </ul>

          <h2 class="text-2xl font-light text-gray-900 mt-8 mb-4">3. Limitation of Liability</h2>
          <ul class="text-gray-700 leading-relaxed mb-6 space-y-2">
            <li>We provide our services on an "as is" and "as available" basis without any warranties, express or implied.</li>
            <li>We are not responsible for any damages or losses resulting from the use of our website, including but not limited to loss of data, security issues, or financial losses.</li>
            <li>We do not guarantee continuous, uninterrupted access to our services.</li>
          </ul>

          <h2 class="text-2xl font-light text-gray-900 mt-8 mb-4">4. User Responsibilities</h2>
          <ul class="text-gray-700 leading-relaxed mb-6 space-y-2">
            <li>You agree not to use our website for any unlawful, fraudulent, or abusive activities.</li>
            <li>You may not use our services to generate or distribute harmful, misleading, or illegal content.</li>
          </ul>

          <h2 class="text-2xl font-light text-gray-900 mt-8 mb-4">5. Privacy & Data Usage</h2>
          <ul class="text-gray-700 leading-relaxed mb-6 space-y-2">
            <li>We may collect and store certain usage data to improve our services. For details, please refer to our Privacy Policy.</li>
            <li>We do not store or track any personally identifiable information generated by users unless explicitly stated.</li>
          </ul>

          <h2 class="text-2xl font-light text-gray-900 mt-8 mb-4">6. Modifications to Terms</h2>
          <ul class="text-gray-700 leading-relaxed mb-6 space-y-2">
            <li>We reserve the right to modify these Terms of Use at any time. Updated terms will be posted on this page, and continued use of the website constitutes acceptance of the changes.</li>
          </ul>

          <h2 class="text-2xl font-light text-gray-900 mt-8 mb-4">7. Governing Law</h2>
          <ul class="text-gray-700 leading-relaxed mb-6 space-y-2">
            <li>These terms shall be governed by and interpreted in accordance with the laws of [Your Jurisdiction]. Any disputes arising from these terms shall be subject to the exclusive jurisdiction of the courts in [Your Jurisdiction].</li>
          </ul>

          <h2 class="text-2xl font-light text-gray-900 mt-8 mb-4">8. Contact Us</h2>
                      <p class="text-gray-700 leading-relaxed mb-6">If you have any questions about these Terms of Use, please contact us at <strong>support@randomaddress.com</strong>.</p>

          <p class="text-gray-700 leading-relaxed">By using <strong>RandomAddress.com</strong>, you acknowledge that you have read, understood, and agreed to these Terms of Use.</p>
        </div>
      </div>
    </div>
  </main>

  <?php echo $footer; ?>

</body>
</html>